/* Room chat uses native text controls on phones and textContent for all messages. */
(()=>{
 let enabled=false,last='',local='',pending='',unread=0,seen=0;
 const style=document.createElement('style');style.textContent=`#ooze-chat-toggle{position:fixed;z-index:650;right:max(10px,env(safe-area-inset-right));top:max(68px,env(safe-area-inset-top));min-width:80px;min-height:44px;background:#071e2bea;color:#8cffff;border:1px solid #1ee4ed;font:700 17px system-ui;touch-action:manipulation}#ooze-chat{position:fixed;z-index:1250;right:max(8px,env(safe-area-inset-right));top:8px;width:min(390px,94vw);height:min(510px,calc(100dvh - 16px));box-sizing:border-box;background:#04121bf5;color:#edffff;border:2px solid #16dbe8;display:flex;flex-direction:column;font:16px system-ui;touch-action:auto}#ooze-chat header{display:flex;align-items:center;justify-content:space-between;padding:8px 12px;font-weight:bold}#ooze-chat button{min-height:44px;padding:8px 14px;background:#16dbe8;color:#001820;border:0;font:700 16px system-ui;touch-action:manipulation}#ooze-chat-log{overflow-y:auto;overscroll-behavior:contain;touch-action:pan-y;flex:1;padding:0 12px;min-height:40px}#ooze-chat-log p{margin:10px 0;white-space:pre-wrap;overflow-wrap:anywhere}#ooze-chat-log strong{display:block;color:#70e9ef;font-size:13px}#ooze-chat form{display:flex;gap:6px;padding:10px}#ooze-chat input{min-width:0;flex:1;font:18px system-ui;padding:10px;background:#0d2632;color:white;border:1px solid #648b9d;user-select:text;-webkit-user-select:text;touch-action:auto}#ooze-chat-status{font-size:13px;padding:0 12px 8px;color:#bed0d5}`;document.head.appendChild(style);
 const toggle=document.createElement('button');toggle.id='ooze-chat-toggle';toggle.textContent='Chat';toggle.hidden=true;
 let panel,log,input,status;
 function close(){panel?.remove();panel=null;document.getElementById('canvas')?.focus()}
 function render(){if(!log||!panel)return;const bottom=log.scrollHeight-log.scrollTop-log.clientHeight<48;log.replaceChildren();for(const m of JSON.parse(last||'[]')){const row=document.createElement('p'),name=document.createElement('strong'),body=document.createElement('span');name.textContent=(m.faction===local?'You':String(m.faction).toUpperCase());body.textContent=String(m.text);row.append(name,body);log.append(row)}if(bottom)log.scrollTop=log.scrollHeight;unread=0;toggle.textContent='Chat'}
 function open(){if(panel){close();return}panel=document.createElement('section');panel.id='ooze-chat';panel.setAttribute('aria-label','Room chat');const head=document.createElement('header');head.textContent='ROOM CHAT';const exit=document.createElement('button');exit.type='button';exit.textContent='Close';exit.onclick=close;head.append(exit);log=document.createElement('div');log.id='ooze-chat-log';log.setAttribute('role','log');const form=document.createElement('form');input=document.createElement('input');input.type='text';input.maxLength=256;input.placeholder='Message everyone';input.setAttribute('aria-label','Chat message');input.autocomplete='off';const send=document.createElement('button');send.type='submit';send.textContent='Send';status=document.createElement('div');status.id='ooze-chat-status';status.textContent='Visible to everyone in this room. Match keeps running.';form.onsubmit=e=>{e.preventDefault();const text=input.value.trim();if(text){pending=text;input.value='';status.textContent='Visible to everyone in this room. Match keeps running.'}};form.append(input,send);panel.append(head,log,form,status);panel.addEventListener('keydown',e=>e.stopPropagation());document.body.append(panel);render();log.scrollTop=log.scrollHeight;input.focus()}
 toggle.onclick=open;
 function mount(){if(!toggle.isConnected)document.body.append(toggle)}
 window.OozeChat={sync(active,history,faction){mount();enabled=active;toggle.hidden=!active;local=faction;if(!active){close();last='';seen=0;unread=0;pending='';toggle.textContent='Chat';return}if(history!==last){const entries=JSON.parse(history);const latest=entries.length?Number(entries.at(-1).id):0;if(!panel)unread+=entries.filter(m=>Number(m.id)>seen&&m.faction!==local).length;seen=latest;last=history;toggle.textContent=unread?'Chat ('+unread+')':'Chat';render()}},takeMessage(){const value=pending;pending='';return value},error(message){if(status&&panel)status.textContent=message}};
})();
